#!/bin/sh

counter=0
out() {
  if [ $counter -eq 4 ]
  then
    echo "</div>"
    echo "<div class=\"row\">"
    counter=0
  fi
  counter=$((counter + 1))
  echo "<div class=\"cell\">"
  echo "<img class=\"thumb\" src=\"media/.c/$1\">"
  echo "<p>A damn fine caption</p>"
  echo "</div>"
}

begin() {
  echo "<div class=\"row\">"
}

end() {
  echo "</div>"
}

begin > images.html
for i in `ls *.JPG`
do
  echo "$i"
  out $i >> images.html
done
end >> images.html


