name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: sh build.sh
      
      - name: Upload artifacts for download
        uses: actions/upload-artifact@v3
        with:
          name: yadfig
          path: yadfig
